[package]
name = "ntex-dvi"
description = "NTex DVI 写出器（M3-5）"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ntex-layout.workspace = true
ntex-font.workspace = true
ntex-io.workspace = true
ntex-format.workspace = true
ntex-pkg.workspace = true

[lints]
workspace = true
