/// M1 原语集（随里程碑扩充）。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum Primitive {
    Def = 1,
    Edef,
    Gdef,
    Let,
    Relax,
    Expandafter,
    Noexpand,
    Catcode,
    End,
    // M1-7 扫描顺序原语
    Futurelet,
    Aftergroup,
    Afterassignment,
    // M1-9 条件原语
    If,
    IfCat,
    IfNum,
    IfDim,
    IfX,
    IfOdd,
    IfCase,
    IfTrue,
    IfFalse,
    Else,
    Fi,
    Or,
    // M1-10 寄存器
    Count,
    Dimen,
    Skip,
    Toks,
    The,
    Global,
    // M1-11 组
    BeginGroup,
    EndGroup,
    // M3-2 排版原语：参数扫描在 VM 侧（结果经 sink 输出）；
    // hbox/vbox/vtop/par 直通 sink 由排版器解释。
    HBox,
    VBox,
    VTop,
    HSkip,
    VSkip,
    Kern,
    Penalty,
    HRule,
    VRule,
    Par,
    // M3-2-2 内部参数与段落
    ParIndent,
    BaselineSkip,
    LineSkip,
    LineSkipLimit,
    Indent,
    NoIndent,
    // M3-3 折行参数
    HSize,
    Tolerance,
    // M3-4 字体：\font<cs>=<名字>[at/scaled]
    Font,
    // M3-5 输出：\shipout<box>（直通 sink，由排版器封装页面）
    ShipOut,
    // M3-5 断页参数：\vsize/\topskip/\maxdepth/\parskip
    VSize,
    TopSkip,
    MaxDepth,
    ParSkip,
    // M3-4 词间距：\sfcode<字符>=<spacefactor>
    SfCode,
    // M3-5-3 输出例程：\output=<general text>（token 列表存储）；\box<n>（盒子寄存器）
    Output,
    Box,
    // M3 收尾（RFC-3）：VFS 副作用原语
    Input,
    OpenIn,
    CloseIn,
    NewRead,
    Read,
    NewWrite,
    OpenOut,
    CloseOut,
    Write,
    Immediate,
    // M4-2 数学原语（直通 sink，由排版器解释）
    DisplayStyle,
    TextStyle,
    ScriptStyle,
    ScriptScriptStyle,
    Over,
    Atop,
    Left,
    Right,
    Sqrt,
    MathOrd,
    MathBin,
    MathOp,
    MathRel,
    MathOpen,
    MathClose,
    MathPunct,
    MathInner,
    Nonscript,
    // M4-5 e-TeX 展开扩展
    Protected,
    IfDefined,
    IfCsname,
    Unless,
    NumExpr,
    Detokenize,
    Unexpanded,
    ETeXVersion,
    ETeXRevision,
    // M4-3 数学字体族
    TextFont,
    ScriptFont,
    ScriptScriptFont,
    // M4-6 断字：\patterns 模式表
    Patterns,
    // M4-4 显示数学间距参数
    AboveDisplaySkip,
    BelowDisplaySkip,
    AboveDisplayShortSkip,
    BelowDisplayShortSkip,
    PreDisplayPenalty,
    PostDisplayPenalty,
    // M4-5 e-TeX 扩展：\dimexpr/\glueexpr/\ifprimitive/\scantokens
    Dimexpr,
    Glueexpr,
    IfPrimitive,
    Scantokens,
    // ETRIP 冲刺：TeX 内部整数参数
    EndlineChar,
    NewlineChar,
    DefaultHyphenChar,
    DefaultSkewChar,
    // ETRIP 冲刺：宏定义前缀与变体
    Outer,
    Xdef,
    // ETRIP 冲刺：内部只读整数
    Badness,
    // ETRIP 冲刺：字体参数
    FontDimen,
    // ETRIP 冲刺：终端转录原语
    Message,
    Show,
    ShowThe,
    // ETRIP 冲刺：\number 可展开原语
    Number,
    // ETRIP 冲刺：TeX/e-TeX 内部整数参数（值存 Params.misc，按下标索引）
    TracingStats,
    TracingLostChars,
    TracingOnline,
    TracingCommands,
    TracingRestores,
    TracingAssigns,
    TracingGroups,
    TracingIfs,
    TracingScantokens,
    TracingNesting,
    LeftHyphenMin,
    RightHyphenMin,
    HBadness,
    PreTolerance,
    ShowBoxDepth,
    ShowBoxBreadth,
    Language,
    SavingHyphCodes,
    SavingVDiscards,
    InteractionMode,
    TeXXeTState,
    MathSurround,
    LastLineFit,
    PredisplayDirection,
    EveryEof,
    // ETRIP 冲刺：交互模式命令（\batchmode/\nonstopmode/\scrollmode/\errorstopmode）
    BatchMode,
    NonstopMode,
    ScrollMode,
    ErrorStopMode,
    // ETRIP 冲刺：\chardef/\countdef/\dimendef/\skipdef/\toksdef（cs 绑定字符/寄存器）
    Chardef,
    Countdef,
    Dimendef,
    Skipdef,
    Toksdef,
    // ETRIP 冲刺：\hyphenchar<font>=<int>（字体断字符）
    HyphenChar,
    // ETRIP 冲刺：\delcode<num>=<num>（字符定界符码）
    DelCode,
    // ETRIP 冲刺：\muskip/\muskipdef（mu 胶量寄存器；1mu = 65536 单位）
    Muskip,
    Muskipdef,
    // ETRIP 冲刺：\thinmuskip/\medmuskip/\thickmuskip（muskip 寄存器 0/1/2）
    ThinMuskip,
    MedMuskip,
    ThickMuskip,
    // ETRIP 冲刺：\lccode<char>=<num>（小写码表）
    LcCode,
    // ETRIP 冲刺：\advance<寄存器> <增量>（寄存器运算）
    Advance,
    // ETRIP 冲刺：\hyphenation{...}（断字异常词表；按语言存，断字时优先于 patterns）
    Hyphenation,
    // ETRIP 冲刺：\setbox<n>=<box>（盒子寄存器赋值）
    SetBox,
    // ETRIP 冲刺：\parfillskip（段落末行填充胶水）
    ParFillSkip,
    // ETRIP 冲刺：\␣（control space，输出一个空格 token）
    ControlSpace,
    // ETRIP 冲刺：无限阶胶水 \hfil/\hfill/\hss/\vfil/\vfill/\vss
    HFil,
    HFill,
    HSS,
    VFil,
    VFill,
    VSS,
    // ETRIP 冲刺：\vsplit<n> to/spread <dimen>（纵向拆分盒子寄存器）
    VSplit,
    // ETRIP 冲刺：\everyjob=<tokens>（作业开始 token 表；暂映射 toks 0）
    EveryJob,
    // ETRIP 冲刺：\dump（initex 收尾：写 fmt + 结束作业）
    Dump,
    // ETRIP 冲刺：TeXXeT 方向原语 \beginL/\endL/\beginR/\endR（方向节点）
    BeginL,
    EndL,
    BeginR,
    EndR,
    // e-TeX（M4-5）：\middle<delimiter>（\left...\right 内分隔符）
    Middle,
    // ETRIP 冲刺：\mark<general text>（mark 节点）与 e-TeX \marks<n><general text>
    Mark,
    Marks,
    // ETRIP 冲刺：\showbox<n>（显示盒子寄存器内容）
    ShowBox,
    // ETRIP 冲刺：\inputlineno（当前输入行号；只读整数）与 \string<token>（token 转文本）
    InputLineNo,
    String_,
    // ETRIP 冲刺：e-TeX 内部只读整数 \currentgrouplevel/\currentgrouptype/\lastnodetype
    CurrentGroupLevel,
    CurrentGroupType,
    LastNodeType,
    // ETRIP 冲刺：\discretionary{pre}{post}{replace}（断字节点）
    Discretionary,
    // ETRIP 冲刺：\insert<num>{<general text>}（insert 节点）与 \vadjust{...}（adjust 节点）
    Insert,
    VAdjust,
    // ETRIP 冲刺：对齐 \valign/\halign/\cr/\noalign 与 \mathchoice{}{}{}{}
    Valign,
    Halign,
    Cr,
    NoAlign,
    MathChoice,
    // ETRIP 冲刺：输出例程 \deadcycles；\tracingmacros/\tracingoutput/\errorcontextlines
    DeadCycles,
    TracingMacros,
    TracingOutput,
    ErrorContextLines,
    // ETRIP 冲刺：\raise/\lower<dimen><box>（盒子参考点位移）与 \span（对齐模板）
    Raise,
    Lower,
    Span,
    // ETRIP 冲刺：\special{<general text>}（whatsit 节点）与 \jobname（作业名）
    Special,
    JobName,
    // ETRIP 冲刺：\vcenter<box>（数学垂直居中盒，简化按 vbox）
    VCenter,
    // ETRIP 冲刺：\ifinner（内部垂直/受限水平/数学模式为真；TeX 条件原语）
    IfInner,
    // ETRIP 冲刺：\csname...\endcsname（构造控制序列名，可展开）
    Csname,
    EndCsname,
    // ETRIP 冲刺：模式/盒子/EOF 条件原语（\ifvmode/\ifhmode/\ifmmode/\ifeof/\ifvoid/\ifhbox/\ifvbox）
    IfVMode,
    IfHMode,
    IfMMode,
    IfEof,
    IfVoid,
    IfHBox,
    IfVBox,
    // ETRIP 冲刺：寄存器算术（\multiply/\divide）
    Multiply,
    Divide,
    // ETRIP 冲刺：e-TeX 只读整数（\currentiflevel/\currentiftype/\currentifbranch）
    CurrentIfLevel,
    CurrentIfType,
    CurrentIfBranch,
    // ETRIP 冲刺：\meaning<token>（可展开：token 含义文本）与 \mathchardef\cs=<num>
    Meaning,
    MathCharDef,
    // ETRIP 冲刺：胶水分量查询（\gluestretchorder/\glueshrinkorder 整数上下文、
    // \gluestretch/\glueshrink 尺寸上下文）
    GlueStretchOrder,
    GlueShrinkOrder,
    GlueStretch,
    GlueShrink,
    // ETRIP 冲刺：\showtokens{<text>}（显示展开后的 token 列表）与 \readline<n>to\cs
    ShowTokens,
    ReadLine,
    // ETRIP 冲刺：字体字符查询（\iffontchar 条件 + \fontcharwd/ht/dp/ic 度量）与
    // \showifs（显示条件嵌套）
    IfFontChar,
    FontCharWd,
    FontCharHt,
    FontCharDp,
    FontCharIc,
    ShowIfs,
    // ETRIP 冲刺：段落形状（\parshape 赋值 + \parshapelength/indent/dimen 读取）
    Parshape,
    ParshapeLength,
    ParshapeIndent,
    ParshapeDimen,
    // ETRIP 冲刺：e-TeX marks 族查询（可展开，返回字符 token 文本）
    TopMarks,
    FirstMarks,
    BotMarks,
    SplitFirstMarks,
    SplitTopMarks,
    SplitBotMarks,
    // ETRIP 第二波：e-TeX mu 转换原语（可展开，参数为 mu/skip 胶水，输出胶水/mu 胶水 token）
    MuToGlue,
    GlueToMu,
    // ETRIP 第二波：e-TeX 惩罚数组（\interlinepenalties n p1 p2 ... pn 等）
    InterLinePenalties,
    ClubPenalties,
    WidowPenalties,
    DisplayWidowPenalties,
    // ETRIP 第二波：e-TeX 丢弃物控制整数（misc 数组）
    PageDiscards,
    SplitDiscards,
    LostChars,
    // ETRIP 第二波：盒子复制/拆包原语（\copy/\unhbox/\unvbox/\unhcopy/\unvcopy/\lastbox）
    Copy,
    UnHBox,
    UnVBox,
    UnHCopy,
    UnVCopy,
    LastBox,
    // ETRIP 第二波：盒子尺寸查询/赋值（\wd/\ht/\dp，可展开读尺寸）
    Wd,
    Ht,
    Dp,
    // ETRIP 第二波：段落/断页参数原语（胶水/尺寸/整数参数）
    LeftSkip,
    RightSkip,
    PrevDepth,
    InterLinePenalty,
    ClubPenalty,
    WidowPenalty,
    DisplayWidowPenalty,
    // ETRIP 第二波：列表尾操作（\unskip/\lastpenalty/\unpenalty；\lastpenalty 可展开读整数）
    UnSkip,
    LastPenalty,
    UnPenalty,
    // ETRIP 第二波：诊断原语（\showgroups/\showlists）
    ShowGroups,
    ShowLists,
    // ETRIP 第二波：折行追踪整数参数（misc 数组）
    TracingParagraphs,
    // ETRIP 第二波：对齐模板跳过（\omit；简化为 no-op，由对齐组后续实现语义）
    Omit,
    // TRIP：\mag（放大倍数整数参数；L67 赋值 2000，L160 `.5\mag` 作 dimen 乘子）
    Mag,
    // TRIP 冲刺：dimen 内部参数（initex 预定义）
    NullDelimiterSpace,
    ScriptSpace,
    OverfullRule,
    VOffset,
    HOffset,
    // TRIP 冲刺：\mathcode（字符数学码表）
    MathCode,
    // TRIP 冲刺：\noboundary（数学字符边界抑制；水平/垂直模式 no-op）
    NoBoundary,
    // TRIP 冲刺：\moveleft/\moveright<dimen><box>（盒子水平位移）
    MoveLeft,
    MoveRight,
    // TRIP 冲刺：\accent<8-bit number><字符>（读音符；数学模式报错恢复）
    Accent,
    // TRIP 冲刺：\vfilneg（plain.tex：负 1fil 的 vskip）
    VFilNeg,
    // TRIP 冲刺：\hfilneg（plain.tex：负 1fil 的 hskip）
    HFilNeg,
    // TRIP 冲刺：\error（plain.tex 宏：errmessage；TRIP L402 分支不执行）
    Error,
    // TRIP 冲刺：\varunit（plain.tex 字体标识符；TRIP L404 `\fontdimen1000=20\varunit`）
    VarUnit,
    // TRIP 冲刺：\xspaceskip（plain.tex 胶水参数；TRIP L410 `\advance\xspaceskip by-\xspaceskip`）
    XSpaceSkip,
    // TRIP 冲刺：\spacefactor（活空间因子；由排版器维护，赋值/读取实时经 sink）
    SpaceFactor,
    // TRIP 冲刺：\everymath（进入数学模式时注入的 token 列表；VM 存储）
    EveryMath,
    // TRIP 冲刺：\/（斜体校正；水平模式发 kern，数学模式为斜体校正原子）
    ItalicCorrection,
    // TRIP 冲刺：\radical<delimiter><math field>（根式原子，\sqrt 底层，带定界符号）
    Radical,
    // TRIP 冲刺：\delimiterfactor（内部整数参数，misc 数组；delimiter 缩放因子，默认 901）
    DelimiterFactor,
}

impl Primitive {
    /// 参与展开的原语（其余为不可展开，直接执行）。
    ///
    /// TeX 可展开集：`\expandafter`/`\noexpand`/`\the`/`\number`、
    /// e-TeX `\unexpanded`/`\detokenize`/`\eTeXversion`/`\eTeXrevision`；
    /// 条件原语由 process_one 单独拦截（\edef 中同样展开）。
    pub fn is_expandable(self) -> bool {
        matches!(
            self,
            Self::Expandafter
                | Self::Noexpand
                | Self::The
                | Self::Number
                | Self::Unexpanded
                | Self::Detokenize
                // \eTeXrevision 可展开（→".6"，etrip 版本宏习语 `\number\eTeXversion\eTeXrevision`）；
                // \eTeXversion 是内部整数（非可展开），`\the\eTeXversion` 由 the_tokens_after 直读。
                | Self::ETeXRevision
                | Self::String_
                | Self::JobName
                | Self::Csname
                // ETRIP 冲刺：\meaning<token>（TeX 可展开原语）
                | Self::Meaning
                // ETRIP 冲刺：e-TeX marks 族查询（可展开：返回字符 token 文本）
                | Self::TopMarks
                | Self::FirstMarks
                | Self::BotMarks
                | Self::SplitFirstMarks
                | Self::SplitTopMarks
                | Self::SplitBotMarks
        )
    }

    /// 原始值（`.fmt` 快照序列化；变体自 1 起连续）。
    pub const fn as_u16(self) -> u16 {
        self as u16
    }

    /// 从原始值恢复（`.fmt` 快照反序列化）。
    pub const fn from_u16(v: u16) -> Option<Self> {
        Some(match v {
            1 => Self::Def,
            2 => Self::Edef,
            3 => Self::Gdef,
            4 => Self::Let,
            5 => Self::Relax,
            6 => Self::Expandafter,
            7 => Self::Noexpand,
            8 => Self::Catcode,
            9 => Self::End,
            10 => Self::Futurelet,
            11 => Self::Aftergroup,
            12 => Self::Afterassignment,
            13 => Self::If,
            14 => Self::IfCat,
            15 => Self::IfNum,
            16 => Self::IfDim,
            17 => Self::IfX,
            18 => Self::IfOdd,
            19 => Self::IfCase,
            20 => Self::IfTrue,
            21 => Self::IfFalse,
            22 => Self::Else,
            23 => Self::Fi,
            24 => Self::Or,
            25 => Self::Count,
            26 => Self::Dimen,
            27 => Self::Skip,
            28 => Self::Toks,
            29 => Self::The,
            30 => Self::Global,
            31 => Self::BeginGroup,
            32 => Self::EndGroup,
            33 => Self::HBox,
            34 => Self::VBox,
            35 => Self::VTop,
            36 => Self::HSkip,
            37 => Self::VSkip,
            38 => Self::Kern,
            39 => Self::Penalty,
            40 => Self::HRule,
            41 => Self::VRule,
            42 => Self::Par,
            43 => Self::ParIndent,
            44 => Self::BaselineSkip,
            45 => Self::LineSkip,
            46 => Self::LineSkipLimit,
            47 => Self::Indent,
            48 => Self::NoIndent,
            49 => Self::HSize,
            50 => Self::Tolerance,
            51 => Self::Font,
            52 => Self::ShipOut,
            53 => Self::VSize,
            54 => Self::TopSkip,
            55 => Self::MaxDepth,
            56 => Self::ParSkip,
            57 => Self::SfCode,
            58 => Self::Output,
            59 => Self::Box,
            60 => Self::Input,
            61 => Self::OpenIn,
            62 => Self::CloseIn,
            63 => Self::NewRead,
            64 => Self::Read,
            65 => Self::NewWrite,
            66 => Self::OpenOut,
            67 => Self::CloseOut,
            68 => Self::Write,
            69 => Self::Immediate,
            70 => Self::DisplayStyle,
            71 => Self::TextStyle,
            72 => Self::ScriptStyle,
            73 => Self::ScriptScriptStyle,
            74 => Self::Over,
            75 => Self::Atop,
            76 => Self::Left,
            77 => Self::Right,
            78 => Self::Sqrt,
            79 => Self::MathOrd,
            80 => Self::MathBin,
            81 => Self::MathOp,
            82 => Self::MathRel,
            83 => Self::MathOpen,
            84 => Self::MathClose,
            85 => Self::MathPunct,
            86 => Self::MathInner,
            87 => Self::Nonscript,
            88 => Self::Protected,
            89 => Self::IfDefined,
            90 => Self::IfCsname,
            91 => Self::Unless,
            92 => Self::NumExpr,
            93 => Self::Detokenize,
            94 => Self::Unexpanded,
            95 => Self::ETeXVersion,
            96 => Self::ETeXRevision,
            97 => Self::TextFont,
            98 => Self::ScriptFont,
            99 => Self::ScriptScriptFont,
            100 => Self::Patterns,
            101 => Self::AboveDisplaySkip,
            102 => Self::BelowDisplaySkip,
            103 => Self::AboveDisplayShortSkip,
            104 => Self::BelowDisplayShortSkip,
            105 => Self::PreDisplayPenalty,
            106 => Self::PostDisplayPenalty,
            107 => Self::Dimexpr,
            108 => Self::Glueexpr,
            109 => Self::IfPrimitive,
            110 => Self::Scantokens,
            111 => Self::EndlineChar,
            112 => Self::NewlineChar,
            113 => Self::DefaultHyphenChar,
            114 => Self::DefaultSkewChar,
            115 => Self::Outer,
            116 => Self::Xdef,
            117 => Self::Badness,
            118 => Self::FontDimen,
            119 => Self::Message,
            120 => Self::Show,
            121 => Self::ShowThe,
            122 => Self::Number,
            123 => Self::TracingStats,
            124 => Self::TracingLostChars,
            125 => Self::TracingOnline,
            126 => Self::TracingCommands,
            127 => Self::TracingRestores,
            128 => Self::TracingAssigns,
            129 => Self::TracingGroups,
            130 => Self::TracingIfs,
            131 => Self::TracingScantokens,
            132 => Self::TracingNesting,
            133 => Self::LeftHyphenMin,
            134 => Self::RightHyphenMin,
            135 => Self::HBadness,
            136 => Self::PreTolerance,
            137 => Self::ShowBoxDepth,
            138 => Self::ShowBoxBreadth,
            139 => Self::Language,
            140 => Self::SavingHyphCodes,
            141 => Self::SavingVDiscards,
            142 => Self::InteractionMode,
            143 => Self::TeXXeTState,
            144 => Self::MathSurround,
            145 => Self::LastLineFit,
            146 => Self::PredisplayDirection,
            147 => Self::EveryEof,
            148 => Self::BatchMode,
            149 => Self::NonstopMode,
            150 => Self::ScrollMode,
            151 => Self::ErrorStopMode,
            152 => Self::Chardef,
            153 => Self::Countdef,
            154 => Self::Dimendef,
            155 => Self::Skipdef,
            156 => Self::Toksdef,
            157 => Self::HyphenChar,
            158 => Self::DelCode,
            159 => Self::Muskip,
            160 => Self::Muskipdef,
            161 => Self::ThinMuskip,
            162 => Self::MedMuskip,
            163 => Self::ThickMuskip,
            164 => Self::LcCode,
            165 => Self::Advance,
            166 => Self::Hyphenation,
            167 => Self::SetBox,
            168 => Self::ParFillSkip,
            169 => Self::ControlSpace,
            170 => Self::HFil,
            171 => Self::HFill,
            172 => Self::HSS,
            173 => Self::VFil,
            174 => Self::VFill,
            175 => Self::VSS,
            176 => Self::VSplit,
            177 => Self::EveryJob,
            178 => Self::Dump,
            179 => Self::BeginL,
            180 => Self::EndL,
            181 => Self::BeginR,
            182 => Self::EndR,
            183 => Self::Middle,
            184 => Self::Mark,
            185 => Self::Marks,
            186 => Self::ShowBox,
            187 => Self::InputLineNo,
            188 => Self::String_,
            189 => Self::CurrentGroupLevel,
            190 => Self::CurrentGroupType,
            191 => Self::LastNodeType,
            192 => Self::Discretionary,
            193 => Self::Insert,
            194 => Self::VAdjust,
            195 => Self::Valign,
            196 => Self::Halign,
            197 => Self::Cr,
            198 => Self::NoAlign,
            199 => Self::MathChoice,
            200 => Self::DeadCycles,
            201 => Self::TracingMacros,
            202 => Self::TracingOutput,
            203 => Self::ErrorContextLines,
            204 => Self::Raise,
            205 => Self::Lower,
            206 => Self::Span,
            207 => Self::Special,
            208 => Self::JobName,
            209 => Self::VCenter,
            210 => Self::IfInner,
            211 => Self::Csname,
            212 => Self::EndCsname,
            213 => Self::IfVMode,
            214 => Self::IfHMode,
            215 => Self::IfMMode,
            216 => Self::IfEof,
            217 => Self::IfVoid,
            218 => Self::IfHBox,
            219 => Self::IfVBox,
            220 => Self::Multiply,
            221 => Self::Divide,
            222 => Self::CurrentIfLevel,
            223 => Self::CurrentIfType,
            224 => Self::CurrentIfBranch,
            225 => Self::Meaning,
            226 => Self::MathCharDef,
            227 => Self::GlueStretchOrder,
            228 => Self::GlueShrinkOrder,
            229 => Self::GlueStretch,
            230 => Self::GlueShrink,
            231 => Self::ShowTokens,
            232 => Self::ReadLine,
            233 => Self::IfFontChar,
            234 => Self::FontCharWd,
            235 => Self::FontCharHt,
            236 => Self::FontCharDp,
            237 => Self::FontCharIc,
            238 => Self::ShowIfs,
            239 => Self::Parshape,
            240 => Self::ParshapeLength,
            241 => Self::ParshapeIndent,
            242 => Self::ParshapeDimen,
            243 => Self::TopMarks,
            244 => Self::FirstMarks,
            245 => Self::BotMarks,
            246 => Self::SplitFirstMarks,
            247 => Self::SplitTopMarks,
            248 => Self::SplitBotMarks,
            // ETRIP 第二波：新原语变体（249-280）
            249 => Self::MuToGlue,
            250 => Self::GlueToMu,
            251 => Self::InterLinePenalties,
            252 => Self::ClubPenalties,
            253 => Self::WidowPenalties,
            254 => Self::DisplayWidowPenalties,
            255 => Self::PageDiscards,
            256 => Self::SplitDiscards,
            257 => Self::LostChars,
            258 => Self::Copy,
            259 => Self::UnHBox,
            260 => Self::UnVBox,
            261 => Self::UnHCopy,
            262 => Self::UnVCopy,
            263 => Self::LastBox,
            264 => Self::Wd,
            265 => Self::Ht,
            266 => Self::Dp,
            267 => Self::LeftSkip,
            268 => Self::RightSkip,
            269 => Self::PrevDepth,
            270 => Self::InterLinePenalty,
            271 => Self::ClubPenalty,
            272 => Self::WidowPenalty,
            273 => Self::DisplayWidowPenalty,
            274 => Self::UnSkip,
            275 => Self::LastPenalty,
            276 => Self::UnPenalty,
            277 => Self::ShowGroups,
            278 => Self::ShowLists,
            279 => Self::TracingParagraphs,
            280 => Self::Omit,
            281 => Self::Mag,
            282 => Self::NullDelimiterSpace,
            283 => Self::ScriptSpace,
            284 => Self::OverfullRule,
            285 => Self::VOffset,
            286 => Self::HOffset,
            287 => Self::MathCode,
            288 => Self::NoBoundary,
            289 => Self::MoveLeft,
            290 => Self::MoveRight,
            291 => Self::Accent,
            292 => Self::VFilNeg,
            293 => Self::Error,
            294 => Self::VarUnit,
            295 => Self::HFilNeg,
            296 => Self::XSpaceSkip,
            // TRIP 冲刺：\spacefactor/\everymath/\/\radical/\delimiterfactor（297-301）
            297 => Self::SpaceFactor,
            298 => Self::EveryMath,
            299 => Self::ItalicCorrection,
            300 => Self::Radical,
            301 => Self::DelimiterFactor,
            _ => return None,
        })
    }
}
